lib/klik/web/router.ex
defmodule Klik.Web.Router do
  use Klik.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers, %{
      "content-security-policy" => Application.get_env(:klik, :csp)
    }
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Klik.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/counters", CounterController, except: [:index, :new, :delete] do
      resources "/increments", IncrementController, only: [:create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Klik.Web do
  #   pipe_through :api
  # end
end

lib/klik/web/controllers/counter_controller.ex
defmodule Klik.Web.CounterController do
  use Klik.Web, :controller

  alias Klik.Counters

  def create(conn, _params) do
    case Counters.create_counter() do
      {:ok, counter} ->
        conn
        |> put_flash(:info, "Counter created successfully.")
        |> redirect(to: counter_path(conn, :show, counter))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "There was an error creating counter.")
        |> render("index.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    counter = Counters.get_counter!(id)
    render(conn, "show.html", counter: counter)
  end

  def edit(conn, %{"id" => id}) do
    counter = Counters.get_counter!(id)
    changeset = Counters.change_counter(counter)
    render(conn, "edit.html", counter: counter, changeset: changeset)
  end

  def update(conn, %{"id" => id, "counter" => counter_params}) do
    counter = Counters.get_counter!(id)

    case Counters.update_counter(counter, counter_params) do
      {:ok, counter} ->
        conn
        |> put_flash(:info, "Counter updated successfully.")
        |> redirect(to: counter_path(conn, :show, counter))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", counter: counter, changeset: changeset)
    end
  end
end

lib/klik/web/controllers/increment_controller.ex
defmodule Klik.Web.IncrementController do
  use Klik.Web, :controller
  alias Klik.Counters

  def create(conn, %{"counter_id" => counter_id}) do
    counter = Counters.get_counter!(counter_id)

    case Counters.increment_counter(counter) do
      {:ok, counter, _increment} ->
        conn
        |> redirect(to: counter_path(conn, :show, counter))
      {:error, %Ecto.Changeset{}} ->
        conn
        |> put_flash(:error, "There was an error incrementing the counter.")
        |> redirect(to: counter_path(conn, :show, counter))
    end
  end
end

lib/klik/web/controllers/page_controller.ex
defmodule Klik.Web.PageController do
  use Klik.Web, :controller

  @preloaded_resources [
    {"/css/app.css", "style"},
    {"/fonts/lato.woff2", "font"},
    {"/js/app.js", "script"},
  ]

  def index(conn, _params) do
    conn
    |> put_preload_header(@preloaded_resources)
    |> render("index.html")
  end
end

lib/klik/web/views/component_view.ex
defmodule Klik.Web.ComponentView do
  use Klik.Web, :view
end

lib/klik/web/views/counter_view.ex
defmodule Klik.Web.CounterView do
  use Klik.Web, :view

  def counter_name(%{name: nil}), do: "Counter"
  def counter_name(%{name: name}), do: name

  def channelId(counter) do
    Klik.Web.CounterChannel.id(counter)
  end

  def number_with_leading_zeros(number, length \\ 5) do
    number
    |> Integer.to_string
    |> String.pad_leading(length, "0")
  end

end

lib/klik/web/views/error_view.ex
defmodule Klik.Web.ErrorView do
  use Klik.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/klik/web/views/layout_view.ex
defmodule Klik.Web.LayoutView do
  use Klik.Web, :view
end

lib/klik/web/views/page_view.ex
defmodule Klik.Web.PageView do
  use Klik.Web, :view
end

lib/klik/web/templates/counter/edit.html.eex
<section class="counter-edit">
  <h2>Edit Counter</h2>

  <%= render "form.html",
        changeset: @changeset,
        action: counter_path(@conn, :update, @counter) %>

  <div class="counter-edit__actions"><%= link "Back",
              class: "btn btn--round",
              to: counter_path(@conn, :show, @counter) %></div>
</section>

lib/klik/web/templates/counter/form.html.eex
<%= form_for @changeset, @action, [class: "form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form__group">
    <%= label f, :name, class: "form__label" %>
    <%= text_input f, :name, class: "form__control",
          placeholder: "Counter", maxlength: 36 %>
    <%= error_tag f, :name %>
  </div>

  <div class="form__group">
    <%= submit "Submit", class: "btn btn--primary" %>
  </div>
<% end %>

lib/klik/web/templates/counter/show.html.eex
<section class="counter"
    data-page="counter-show"
    data-counter-id="<%= @counter.id %>"
    data-counter-value="<%= @counter.value %>"
    data-channel-id="<%= channelId(@counter) %>">
  <h2 class="counter__name"><%= counter_name(@counter) %></h2>
  <span class="counter__value"><%= number_with_leading_zeros(@counter.value) %></span>

  <%= form_for @conn, counter_increment_path(@conn, :create, @counter), [as: :increment], fn _ -> %>
    <%= submit class: "counter__button" do %>
      <svg class="counter__button_icon" viewbox="0 0 250 250">
        <g fill-rule="evenodd" >
          <path d="M0,125 a125,125 0 1,0 250,0 a125,125 0 1,0 -250,0 Z
                   M110 55 h30 v55 h55 v30 h-55 v55 h-30 v-55 h-55 v-30 h55 v-55 Z"/>
      </svg>
    <% end %>
  <% end %>

  <div class="counter__actions">
    <%= link "Edit",
          to: counter_path(@conn, :edit, @counter),
          class: "btn btn--round" %>
  </div>
</section>

lib/klik/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Tomek Paczkowski">

    <title>Ninja Clicker</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#feca01">
    <link rel="shortcut icon" href="/icons/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="Ninja Clicker">
    <meta name="application-name" content="Ninja Clicker">
    <meta name="msapplication-config" content="/icons/browserconfig.xml">
    <meta name="theme-color" content="#435969">
  </head>

  <body>
    <header class="header">
      <h1 class="header__title">
        <a class="header__title_link" href="/">Ninja Clicker</a>
      </h1>
    </header>

    <div class="container">
      <!-- <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p> -->
      <!-- <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p> -->

      <main role="main" class="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script async src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/klik/web/templates/page/index.html.eex
<section class="home">
  <div class="home__box">
    <h2 class="home__title">Ninja Clicker</h2>
    <p class="home__lead">Possibly the best clicker app ever</p>

    <hr class="home__break">

    <p>
      <%= form_for @conn, counter_path(@conn, :create), [as: :counter], fn _ -> %>
          <%= submit "Start clicking now!", class: "home__cta" %>
      <% end %>
    </p>
  </div>
</section>